### ISSUE TITLE
Missing API docs

### ISSUE THREAD

**Issue by prushforth** [relaxng/relaxng.org#5]
This [page](https://relaxng.org/jclark/pluggable-datatypes.html) makes reference to API documentation, but it is [404](https://relaxng.org/jclark/api/datatype/index.html).

Great initiative, BTW. 👍

**Comment by ndw** [comment]
Thanks. I don't immediately see what those would have been. Maybe @jclark can shed some light.

**Comment by murata2makoto** [comment]
After I return from Italy, I will search for it.

**Comment by jclark** [comment]
It's built by the Ant javadoc target.

James

**Comment by murata2makoto** [comment]
Unzip the zip file available at this [page](https://sourceforge.net/projects/relaxng/files/datatype%20%28java%29/Ver.1.0/).   Its doc directory contains HTML files generated by javadoc.

**Comment by ndw** [comment]
Thank you! I’m traveling most of today but I’ll do this as soon as I can.

**Comment by prushforth** [comment]
@murata2makoto Thank you! @ndw I have got a local copy, and thanks!
