### ISSUE TITLE
broken links galore on https://relaxng.org/jclark/

### ISSUE THREAD

**Issue by SamB** [relaxng/relaxng.org#8]
See [W3C Link Checker: https://relaxng.org/jclark/](https://validator.w3.org/checklink?uri=https%3A%2F%2Frelaxng.org%2Fjclark%2F&hide_type=all&depth=&check=Check) for a list.

Some of these (most of the non-`.html` ones) are presumably from Jekyll dropping stuff on the floor, and could presumably be fixed by adding a `.nojekyll` at the root of this repository.

Some of them used to get built using rules that are still back in the [jing-trang](https://github.com/relaxng/jing-trang) repository.

The xhtml/ sub-directory also appears to have been left back in jing-trang.

**Comment by sideshowbarker** [comment]
Thanks much — fixed in 4c7f1f7. Please (re)check the site now and let me know if I missed anything
